# Generated by Django 6.0.1 on 2026-04-16 12:53

import core.utils.media
import social_network.validations.video
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Image'), (2, 'Vidéo')])),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.media.get_image_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=core.utils.media.get_image_path, validators=[social_network.validations.video.validate_video])),
            ],
        ),
    ]
