# Generated by Django 6.0.1 on 2026-04-16 13:47

import core.utils.media
import social_network.validations.video
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.media.get_video_path, validators=[social_network.validations.video.validate_video]),
        ),
    ]
