# Generated by Django 6.0.1 on 2026-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_publication_created_at_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
