# Generated by Django 6.0.4 on 2026-04-26 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_create_at_member_created_at'),
        ('social_network', '0004_publication_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.publication')),
            ],
        ),
    ]
