# Generated by Django 6.0.4 on 2026-05-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_client_code'),
        ('social_network', '0008_alter_comment_publication_alter_like_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.member'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='social_network.publication'),
        ),
    ]
