# Generated by Django 6.0.4 on 2026-05-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_comment_member_alter_comment_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_network.publication'),
        ),
    ]
