# Generated by Django 6.0.1 on 2026-01-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercice",
            name="equipments",
        ),
        migrations.AddField(
            model_name="exercice",
            name="equipments",
            field=models.ManyToManyField(
                blank=True, related_name="equipments", to="app.equipment"
            ),
        ),
    ]
