# Generated by Django 6.0.1 on 2026-01-10 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_exercice_equipments_exercice_equipments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.ForeignKey(default='NOT_SPECIFIED', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='genders', to='app.gender'),
        ),
    ]
