# Generated by Django 6.0.1 on 2026-01-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.ForeignKey(default='NOT SPECIFIED', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='genders', to='app.gender'),
        ),
    ]
