# Generated by Django 6.0.1 on 2026-01-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_member_gender_alter_session_exercices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
