# Generated by Django 6.0.1 on 2026-01-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_foodcategory_meettype_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetType',
            new_name='MealType',
        ),
    ]
