# Generated by Django 6.0.1 on 2026-01-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_meettype_mealtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PreferredCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adherence_to_diet_plan', models.FloatField()),
                ('blood_pressure', models.IntegerField()),
                ('cholesterol', models.FloatField()),
                ('daily_caloric_intake', models.IntegerField()),
                ('dietary_nutrient_imbalance_score', models.FloatField()),
                ('glucose', models.FloatField()),
                ('weekly_exercise_hours', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activity')),
                ('allergies', models.ManyToManyField(blank=True, to='app.allergie')),
                ('dietary_restrictions', models.ManyToManyField(blank=True, to='app.dietaryrestriction')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
                ('disease_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diseasetype')),
                ('preferred_cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.preferredcuisine')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recommendation')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.severity')),
            ],
        ),
    ]
