# Generated by Django 6.0.1 on 2026-01-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_activity_allergie_dietaryrestriction_diseasetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrecommendation',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.activity'),
        ),
        migrations.AlterField(
            model_name='dietrecommendation',
            name='disease_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.diseasetype'),
        ),
        migrations.AlterField(
            model_name='dietrecommendation',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.member'),
        ),
        migrations.AlterField(
            model_name='dietrecommendation',
            name='preferred_cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.preferredcuisine'),
        ),
        migrations.AlterField(
            model_name='dietrecommendation',
            name='recommendation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.recommendation'),
        ),
        migrations.AlterField(
            model_name='dietrecommendation',
            name='severity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.severity'),
        ),
    ]
