# Generated by Django 5.2.9 on 2026-02-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_dietrecommendation_client_exercice_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='disease_type',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='preferred_cuisine',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='client',
        ),
        migrations.RemoveField(
            model_name='food',
            name='meal_type',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Allergie',
        ),
        migrations.DeleteModel(
            name='DietaryRestriction',
        ),
        migrations.DeleteModel(
            name='DiseaseType',
        ),
        migrations.DeleteModel(
            name='PreferredCuisine',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='DietRecommendation',
        ),
        migrations.DeleteModel(
            name='Severity',
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='MealType',
        ),
    ]
