# Generated by Django 6.0.2 on 2026-03-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_dietrecommendation_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='objectives',
        ),
    ]
