# Generated by Django 6.0.2 on 2026-03-09 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_member_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='app.member'),
        ),
    ]
