# Generated by Django 6.0.4 on 2026-04-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_objective_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
