# Generated by Django 6.0.4 on 2026-04-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_member_user_alter_member_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
