# Generated by Django 6.0.4 on 2026-04-30 16:00

import app.utils.client_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_exercice_client_alter_session_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='uuid',
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(default=app.utils.client_code.gen_client_code, editable=False, max_length=100, unique=True),
        ),
    ]
