# Generated by Django 6.0.4 on 2026-04-30 16:01

import app.utils.client_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_client_uuid_client_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(default=app.utils.client_code.gen_client_code, editable=False, max_length=6, unique=True),
        ),
    ]
