# Generated by Django 6.0.4 on 2026-04-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_client_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(editable=False, max_length=6, null=True, unique=True),
        ),
    ]
