# Generated by Django 6.0.4 on 2026-04-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_client_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='fat_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='workout_frequency',
            field=models.IntegerField(default=0),
        ),
    ]
