# Generated by Django 6.0.4 on 2026-04-30 16:00

import app.utils.client_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_member_bmi_alter_member_fat_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(default=app.utils.client_code.gen_client_code, editable=False, max_length=100, unique=True),
        ),
    ]
