# Generated by Django 6.0.1 on 2026-05-28 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_client_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective', to='app.objective'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender', to='app.gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level', to='app.level'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='app.subscription'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
