# Generated by Django 6.0.4 on 2026-04-30 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_exercice_client_alter_session_client'),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrecommendation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AlterField(
            model_name='food',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
    ]
