# Generated by Django 6.0.4 on 2026-05-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_dietrecommendation_client_alter_food_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='client',
        ),
    ]
