# Generated by Django 6.0.1 on 2026-01-29 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('context', models.JSONField(default=dict, max_length=2000)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
