# Generated by Django 6.0.1 on 2026-01-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_rename_logs_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('critical', 'CRITICAL'), ('debug', 'DEBUG'), ('error', 'ERROR'), ('info', 'INFO'), ('success', 'SUCCESS'), ('warning', 'WARNING')], default='info', max_length=8),
        ),
    ]
