# Generated by Django 6.0.4 on 2026-04-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_rename_type_log_level_rename_message_log_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
