name: Tests & Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: coverage run -m pytest; coverage xml
      
      - name: Get Coverage - change
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{secrets.GITHUB_TOKEN}}
